# Generated by Django 6.0 on 2025-12-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('department', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Youth', 'Youth'), ('Children', 'Children'), ('Choir', 'Choir'), ('Ushering', 'Ushering')], max_length=50)),
                ('position', models.CharField(choices=[('Member', 'Member'), ('Elder', 'Elder'), ('Deacon', 'Deacon'), ('Pastor', 'Pastor'), ('Worker', 'Worker')], default='Member', max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('baptized', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
