# Generated by Django 6.0 on 2026-01-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_updated_at_member_updated_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('member', 'date', 'service_type'), name='unique_member_attendance_per_service'),
        ),
    ]
