# Generated by Django 6.0 on 2026-01-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_attendance_unique_member_attendance_per_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChurchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('service_type', models.CharField(choices=[('Sunday', 'Sunday Service'), ('Midweek', 'Midweek Service'), ('Prayers', 'Prayers'), ('Prayer Meeting', 'Prayer Meeting'), ('Bible Study', 'Bible Study'), ('Intercessory Prayer', 'Intercessory Prayer'), ('Special Prayer Campaign', 'Special Prayer Campaign'), ('Youth Prayer Gathering', 'Youth Prayer Gathering'), ('Prayer and Testimony', 'Prayer and Testimony')], max_length=30)),
                ('announcements', models.TextField()),
                ('total_attendance', models.PositiveIntegerField()),
                ('men', models.PositiveIntegerField(default=0)),
                ('women', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('offering_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promises_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
