# Generated by Django 6.0 on 2026-01-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_dailychurchreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=150)),
                ('promise_type', models.CharField(choices=[('money', 'Money'), ('item', 'Item')], max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, help_text='Date the member promised to bring the item or money', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='members.dailychurchreport')),
            ],
        ),
    ]
