# Generated by Django 6.0.1 on 2026-01-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_promise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='promise',
            name='fulfilled',
            field=models.BooleanField(default=False, help_text='Mark as fulfilled when promise is completed'),
        ),
    ]
