# Generated by Django 6.0 on 2026-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='display_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
