# Generated by Django 6.0 on 2026-01-30 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_announcement_display_date_announcement_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date'], name='members_inc_date_d0af7f_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_type'], name='members_inc_income__f173bb_idx'),
        ),
    ]
